### ISSUE TITLE
噪声模型

### ISSUE THREAD

**Issue by wzzzslim** [jackzou233/CSR-Net#1]
您好，请问一下，关于基于对比学习的细粒度噪声模型估计的代码是没有公布吗？

**Comment by jackzou233** [comment]
邮件已收到邹云昊

**Comment by wzzzslim** [comment]
您好，我最近在研读您的那篇《基于对比学习的细粒度噪声模型估计》，我现在是一名研二学生，想复现一下您的文章，请问您会公布一下代码吗？有时间可以去向您请教一下吗，感谢！



---- 回复的原邮件 ----
| 发件人 | Yunhao ***@***.***> |
| 日期 | 2023年04月11日 10:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [jackzou233/CSR-Net] 噪声模型 (Issue #1) |

邮件已收到邹云昊

**Comment by yunhao-zou** [comment]
您好，此工作我们还在做进一步的扩展，将在完成后公布代码。同时，您对实现或论文的问题可和我通过邮件讨论（zouyunhao@bit.edu.cn），我会全力帮助
